language: java

# We are running in container-based infrastructure and we don't need sudo
sudo: false

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "ekryd-github"
    token:
      secure: "chOQPlK5gY2Xd36Yp8Kgwfk6AkS0/ZUaKH8wGSKbBX44ggjULYbn11oW3BhlihxBcXRMdJW3+HM/Xg3GC8WlAzuSnaxwPmBdrHDB7cgs2wFr+Rk87iUrYeM0x8CZ0nEQODGhzVVWULbT66K8s/+2HawCOA/0omY2cXI8UO2vmvU="


script: bash scripts/build.sh

jdk:
  - openjdk8
  - oraclejdk11
  - openjdk12

after_success:
  - mvn integration-test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
