language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FECikYsVcJp7gIXK5BHi5508kpafdK9nzC+zSZCoyVGpRosE0hUKZTHBY4ldhhBDsGj0XmCuQgQb5SrVYc5WAzPLPGn85RItClulFn8OQYfMqpwtXQBaFaJZv9NqGq1STxHTH7wzOoP9OpuZVEX5fokQ69Ta8KTRtyXG+frrOYE="
   
install: mvn install

jdk:
  - oraclejdk8

os:
  - linux
  - osx
  
addons:
  coverity_scan:
    project:
      name: "Ekryd/sortpom-maven-plugin"
      description: "Maven plugin that helps the user sort pom.xml"
    notification_email: bjorn.ekryd@gmail.com
    build_command_prepend: "mvn clean -Ddev"
    build_command:   "mvn compile -Ddev -DskipTests=true"
    branch_pattern: coverity_scan
    
after_success:
  - mvn clean test jacoco:report coveralls:report