name: Build plugin under Maven 4.0.0-alpha-4

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Maven 4.0.0-alpha-4

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: 21
          distribution: zulu
      - name: Load Maven 4.0.0-alpha-4
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=4.0.0-alpha-4 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean verify -Dlicense.skip=true -Dmaven.min-version=4.0.0-alpha-4 --no-transfer-progress
