name: Build plugin under Maven 4.0.0-alpha-4

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Maven 4.0.0-alpha-4

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: zulu
      - name: Load Maven 4.0.0-alpha-4
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=4.0.0-alpha-4 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean verify -Dlicense.skip=true -Dmaven.min-version=4.0.0-alpha-4 --no-transfer-progress
